name: home_automation
description: Flutter client for home automation project automate

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_database:
  firebase_core:
  cached_network_image: ^0.5.1
  url_launcher:
  connectivity:
  google_sign_in:
  firebase_auth: 0.6.6
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

# flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icon.png"
  android: true

flutter:
  uses-material-design: true
